### ISSUE TITLE
Fix Seed tests for Windows + MacOS

### ISSUE THREAD

**Issue by theo-s** [theo-s/Rforestry#3]
We can either set the exact values we compare against based on the output of running the tests on a docker container or skip the tests on other platforms.

**Comment by theo-s** [comment]
See the handling in the R tests for this 
[https://github.com/theo-s/Rforestry/blob/master/R/tests/testthat/setup.R](https://github.com/theo-s/Rforestry/blob/master/R/tests/testthat/setup.R)

**Comment by petrovicboban** [comment]
For now, we are escaping it.

`@pytest.mark.skipif(platform.system() == "Darwin", reason="This is expected to fail on MacOS")`

There is another flaky test, test_error in forestry.py, which occasionally fails on macos.
